#!/usr/bin/env python3
"""
Outlier Lab — dashboard renderer — table-first layout.

Table is the primary view. Grid is a toggle. Creators section is a row of chips
that filter the table. Multi-creator ready.
"""
import json
import re
import statistics
import urllib.request
import urllib.error
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
THUMBS = ROOT / "thumbs"
OUT = ROOT / "index.html"

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"


# Load creators from config.json (generated by configure.py).
# Each entry is a dict produced by the setup wizard; we just need the handle here.
def _load_creators():
    import sys
    config_path = ROOT / "config.json"
    if not config_path.exists():
        print(
            "ERROR: config.json not found.\n"
            "Run `python3 configure.py` first to set up your creator list.",
            file=sys.stderr,
        )
        sys.exit(1)
    try:
        data = json.loads(config_path.read_text())
    except json.JSONDecodeError as e:
        print(f"ERROR: config.json is malformed: {e}", file=sys.stderr)
        sys.exit(1)
    handles = [c.get("handle") for c in data.get("creators", []) if c.get("handle")]
    if not handles:
        print(
            "ERROR: config.json has no creators yet.\n"
            "Run `python3 configure.py` and add at least one.",
            file=sys.stderr,
        )
        sys.exit(1)
    return handles


CREATORS = _load_creators()


def load(path):
    with open(path) as f:
        return json.load(f)


def fetch(url, dest):
    if dest.exists() and dest.stat().st_size > 0:
        return True
    try:
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=15) as r:
            dest.write_bytes(r.read())
        return True
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError) as e:
        print(f"  ! fetch failed for {url[:60]}: {e}")
        return False


def first_sentence(text, max_len=200):
    if not text:
        return ""
    text = text.strip()
    m = re.split(r"(?<=[\.\!\?])\s+", text, maxsplit=1)
    out = m[0].strip() if m else text
    return out[:max_len] + ("…" if len(out) > max_len else "")


def hook_of(transcript, caption):
    """Prefer transcript's first sentence (real spoken hook).
    Fall back to caption first line if no transcript."""
    if transcript:
        return first_sentence(transcript, 200)
    if caption:
        return first_sentence(caption, 180)
    return ""


def fmt_num(n):
    if n is None:
        return "—"
    n = int(n)
    if n >= 1_000_000:
        return f"{n/1_000_000:.1f}M"
    if n >= 10_000:
        return f"{n/1_000:.0f}K"
    if n >= 1_000:
        return f"{n/1_000:.1f}K"
    return str(n)


def fmt_dur(seconds):
    if not seconds:
        return "—"
    s = int(round(seconds))
    m, s = divmod(s, 60)
    return f"{m}:{s:02d}" if m else f"{s}s"


def outlier_band(ratio):
    if ratio is None:
        return ("normal", "—", "rgba(255,255,255,.4)")
    if ratio >= 15:
        return ("breakout", "Breakout", "#FF3D6E")
    if ratio >= 5:
        return ("strong", "Replicable", "#FF8A3D")
    if ratio >= 2:
        return ("good", "Working", "#FFD43D")
    return ("normal", "Normal", "rgba(255,255,255,.4)")


def load_creator(handle):
    posts = load(DATA / f"{handle}_posts.json")["items"]
    details = load(DATA / f"{handle}_details.json")["dataset"]["previewItems"][0]
    return posts, details


def main():
    THUMBS.mkdir(parents=True, exist_ok=True)

    # === Pre-pass: queue up all image fetches and run them in parallel ===
    fetch_jobs = []  # (url, dest) tuples
    for handle in CREATORS:
        try:
            details = load(DATA / f"{handle}_details.json")["dataset"]["previewItems"][0]
        except (FileNotFoundError, KeyError, IndexError):
            continue
        purl = details.get("profilePicUrlHD") or details.get("profilePicUrl")
        if purl:
            fetch_jobs.append((purl, THUMBS / f"_profile_{handle}.jpg"))
        try:
            posts = load(DATA / f"{handle}_posts.json")["items"]
        except FileNotFoundError:
            continue
        for p in posts:
            sc = p.get("shortCode") or ""
            thumb_url = p.get("displayUrl")
            if sc and thumb_url:
                fetch_jobs.append((thumb_url, THUMBS / f"{sc}.jpg"))

    pending = [(u, d) for (u, d) in fetch_jobs if not (d.exists() and d.stat().st_size > 0)]
    if pending:
        print(f"downloading {len(pending)} images in parallel (of {len(fetch_jobs)} total)…")
        with ThreadPoolExecutor(max_workers=16) as ex:
            list(ex.map(lambda j: fetch(j[0], j[1]), pending))

    creators = []  # ordered creators metadata
    all_rows = []  # flat list of reels across all creators

    for handle in CREATORS:
        posts, details = load_creator(handle)
        views_list = [p.get("videoPlayCount") or p.get("videoViewCount") or 0 for p in posts]
        median_plays = statistics.median(views_list) if views_list else 0

        profile_url = details.get("profilePicUrlHD") or details.get("profilePicUrl")
        profile_local = THUMBS / f"_profile_{handle}.jpg"
        if profile_url:
            fetch(profile_url, profile_local)
        profile_path = f"thumbs/_profile_{handle}.jpg" if profile_local.exists() else None

        creator_meta = {
            "handle": handle,
            "username": details.get("username") or handle,
            "fullName": details.get("fullName") or "",
            "followers": details.get("followersCount") or 0,
            "posts": details.get("postsCount") or 0,
            "verified": bool(details.get("verified")),
            "profile_pic": profile_path,
            "median_plays": median_plays,
            "reels_in_window": len(posts),
        }
        creators.append(creator_meta)

        for p in posts:
            plays = p.get("videoPlayCount") or p.get("videoViewCount") or 0
            ratio = (plays / median_plays) if median_plays else None
            sc = p.get("shortCode", "unknown")
            thumb_url = p.get("displayUrl")
            thumb_local = THUMBS / f"{sc}.jpg"
            if thumb_url:
                fetch(thumb_url, thumb_local)
            ts = p.get("timestamp")
            posted_dt = datetime.fromisoformat(ts.replace("Z", "+00:00")) if ts else None
            likes = p.get("likesCount") or 0
            comments = p.get("commentsCount") or 0
            band = outlier_band(ratio)
            transcript = p.get("transcript") or ""
            caption = p.get("caption") or ""
            all_rows.append({
                "shortCode": sc,
                "url": p.get("url"),
                "thumb": thumb_local.name if thumb_local.exists() else None,
                "hook": hook_of(transcript, caption),
                "transcript": transcript,
                "caption": caption,
                "plays": plays,
                "likes": likes,
                "comments": comments,
                "engagements": likes + comments,
                "duration": p.get("videoDuration") or 0,
                "posted_human": posted_dt.strftime("%b %-d") if posted_dt else "—",
                "posted_ts": int(posted_dt.timestamp()) if posted_dt else 0,
                "ratio": ratio or 0,
                "band_class": band[0],
                "band_label": band[1],
                "band_color": band[2],
                "creator_handle": handle,
                "creator_username": creator_meta["username"],
                "creator_avatar": profile_path,
                "creator_verified": creator_meta["verified"],
            })

    all_rows.sort(key=lambda r: (r["ratio"], r["posted_ts"]), reverse=True)
    outliers = [r for r in all_rows if r["ratio"] >= 2]

    today = datetime.now().strftime("%A %B %-d, %Y")
    total_plays = sum(r["plays"] for r in all_rows)
    total_engagements = sum(r["engagements"] for r in all_rows)
    median_overall = statistics.median([r["plays"] for r in all_rows]) if all_rows else 0

    # Tag each row with whether a local 3-sec clip is available
    clips_dir = ROOT / "clips"
    available_clips = {p.stem for p in clips_dir.glob("*.mp4")} if clips_dir.exists() else set()
    for r in all_rows:
        r["hasClip"] = r["shortCode"] in available_clips

    reels_payload = json.dumps(all_rows, default=str)
    creators_payload = json.dumps(creators)

    # Grid cards (still available via toggle)
    def card_html(r):
        thumb_src = f"thumbs/{r['thumb']}" if r["thumb"] else ""
        ratio_str = f"{r['ratio']:.1f}×" if r["ratio"] else "—"
        hook_esc = escape(r["hook"]) if r["hook"] else "<em style='opacity:.4'>no hook</em>"
        return f"""
        <article class="card band-{r['band_class']}" data-shortcode="{r['shortCode']}" data-creator="{r['creator_handle']}">
          <button class="thumb" type="button">
            {f'<img src="{escape(thumb_src)}" alt="" loading="lazy">' if thumb_src else '<div class="thumb-missing">no thumb</div>'}
            <span class="play-overlay">▶</span>
            <span class="play-badge">{fmt_num(r['plays'])}</span>
            <span class="band-badge" style="background:{r['band_color']}">{ratio_str} · {r['band_label']}</span>
          </button>
          <div class="meta">
            <div class="creator-row">
              {f'<img src="{escape(r["creator_avatar"])}" class="creator-avatar-sm" alt="">' if r['creator_avatar'] else ''}
              <span>@{escape(r['creator_username'])}</span>
            </div>
            <div class="hook">{hook_esc}</div>
            <div class="stats">
              <span><b>{fmt_num(r['plays'])}</b> plays</span>
              <span>♥ {fmt_num(r['likes'])}</span>
              <span>💬 {fmt_num(r['comments'])}</span>
              <span>⏱ {fmt_dur(r['duration'])}</span>
            </div>
          </div>
        </article>
        """

    cards = "\n".join(card_html(r) for r in all_rows)

    # Creator chips
    def creator_chip(c):
        verified = '<span class="verified">✓</span>' if c["verified"] else ""
        avatar = f'<img src="{escape(c["profile_pic"])}" alt="">' if c["profile_pic"] else '<div class="avatar-fallback"></div>'
        return f"""
        <button class="creator-chip" data-creator="{c['handle']}" type="button">
          {avatar}
          <div class="chip-info">
            <div class="chip-name">@{escape(c['username'])}{verified}</div>
            <div class="chip-stats">{fmt_num(c['followers'])} followers · median {fmt_num(c['median_plays'])} · {c['reels_in_window']} reels</div>
          </div>
        </button>
        """

    creator_chips = "\n".join(creator_chip(c) for c in creators)

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Outlier Lab — {today}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root {{
    --bg: #0a0a0c;
    --bg-2: #14141a;
    --bg-3: #1e1e26;
    --fg: #f4f4f6;
    --fg-dim: rgba(244,244,246,.55);
    --fg-faint: rgba(244,244,246,.32);
    --orange: #FF8A3D;
    --pink: #FF3D6E;
    --yellow: #FFD43D;
    --border: rgba(255,255,255,.08);
    --border-strong: rgba(255,255,255,.16);
  }}
  * {{ box-sizing: border-box; }}
  html, body {{ margin: 0; padding: 0; background: var(--bg); color: var(--fg); font-family: -apple-system, BlinkMacSystemFont, "Inter", "SF Pro Display", system-ui, sans-serif; -webkit-font-smoothing: antialiased; }}
  a {{ color: inherit; text-decoration: none; }}
  button {{ font: inherit; color: inherit; border: 0; background: none; cursor: pointer; padding: 0; }}
  .wrap {{ max-width: 1620px; margin: 0 auto; padding: 28px 36px 80px; }}

  /* ===== HEADER — compact ===== */
  header.hero {{ display: grid; grid-template-columns: 1fr auto; gap: 24px; align-items: end; padding-bottom: 20px; border-bottom: 1px solid var(--border); margin-bottom: 28px; }}
  .eyebrow {{ font-size: 11px; letter-spacing: .18em; text-transform: uppercase; color: var(--fg-faint); margin-bottom: 6px; }}
  h1 {{ font-size: 32px; line-height: 1.1; letter-spacing: -.02em; margin: 0 0 4px; font-weight: 600; }}
  h1 .accent {{ background: linear-gradient(90deg, var(--orange), var(--pink)); -webkit-background-clip: text; background-clip: text; color: transparent; }}
  .sub {{ color: var(--fg-dim); font-size: 13px; max-width: 64ch; }}
  .header-meta {{ text-align: right; font-size: 12px; color: var(--fg-faint); }}
  .header-meta .date {{ font-size: 13px; color: var(--fg-dim); margin-bottom: 2px; }}

  /* ===== CREATORS section ===== */
  .section-title {{ font-size: 11px; letter-spacing: .14em; text-transform: uppercase; color: var(--fg-faint); margin: 0 0 12px; font-weight: 600; }}
  .creators-row {{ display: flex; gap: 12px; overflow-x: auto; padding-bottom: 4px; margin-bottom: 28px; }}
  .creator-chip {{ display: flex; align-items: center; gap: 12px; padding: 10px 16px 10px 10px; background: var(--bg-2); border: 1px solid var(--border); border-radius: 12px; transition: all .15s ease; flex-shrink: 0; text-align: left; }}
  .creator-chip:hover {{ border-color: var(--border-strong); transform: translateY(-1px); }}
  .creator-chip.active {{ border-color: var(--orange); background: linear-gradient(90deg, rgba(255,138,61,.1), rgba(255,138,61,.02)); }}
  .creator-chip img {{ width: 40px; height: 40px; border-radius: 50%; object-fit: cover; }}
  .creator-chip .avatar-fallback {{ width: 40px; height: 40px; border-radius: 50%; background: var(--bg-3); }}
  .chip-name {{ font-size: 14px; font-weight: 600; }}
  .chip-name .verified {{ color: var(--orange); margin-left: 4px; font-size: 11px; }}
  .chip-stats {{ font-size: 11px; color: var(--fg-dim); margin-top: 2px; }}
  .creator-chip.all {{ background: var(--bg-3); }}
  .creator-chip.all .chip-name {{ font-size: 13px; }}

  /* ===== KPI strip — compact ===== */
  .kpis {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin-bottom: 24px; }}
  .kpi {{ background: var(--bg-2); border: 1px solid var(--border); border-radius: 12px; padding: 14px 16px; }}
  .kpi .lab {{ font-size: 9px; letter-spacing: .14em; text-transform: uppercase; color: var(--fg-faint); margin-bottom: 6px; }}
  .kpi .val {{ font-size: 22px; font-weight: 600; letter-spacing: -.01em; }}
  .kpi .val.accent {{ color: var(--orange); }}
  .kpi .delta {{ font-size: 10px; color: var(--fg-dim); margin-top: 2px; }}

  /* ===== View toggle ===== */
  .view-bar {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; gap: 16px; flex-wrap: wrap; }}
  .view-bar .left {{ display: flex; align-items: baseline; gap: 14px; }}
  .view-bar h2 {{ font-size: 18px; font-weight: 600; margin: 0; letter-spacing: -.01em; }}
  .view-bar .count {{ font-size: 12px; color: var(--fg-faint); }}
  .view-toggle {{ display: inline-flex; gap: 4px; background: var(--bg-2); border: 1px solid var(--border); border-radius: 999px; padding: 3px; }}
  .view-toggle button {{ padding: 6px 14px; border-radius: 999px; font-size: 11px; font-weight: 600; letter-spacing: .04em; color: var(--fg-dim); transition: all .15s; }}
  .view-toggle button.active {{ background: var(--fg); color: var(--bg); }}
  .view-toggle button:not(.active):hover {{ color: var(--fg); }}
  .filter-status {{ font-size: 11px; color: var(--fg-faint); }}
  .filter-status .pill {{ display: inline-flex; align-items: center; gap: 4px; padding: 3px 8px; border-radius: 999px; background: rgba(255,138,61,.15); color: var(--orange); margin-left: 6px; }}
  .filter-status .pill button {{ color: var(--orange); font-size: 12px; }}

  /* ===== View visibility ===== */
  body[data-view="grid"] .table-view {{ display: none; }}
  body[data-view="table"] .grid-view {{ display: none; }}

  /* ===== TABLE — the main event ===== */
  .table-wrap {{ background: var(--bg-2); border: 1px solid var(--border); border-radius: 14px; overflow: hidden; }}
  table.reels-table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  table.reels-table thead th {{ background: var(--bg-3); padding: 13px 14px; text-align: left; font-size: 10px; letter-spacing: .12em; text-transform: uppercase; color: var(--fg-faint); font-weight: 600; border-bottom: 1px solid var(--border); user-select: none; white-space: nowrap; position: sticky; top: 0; z-index: 1; }}
  table.reels-table thead th[data-sort] {{ cursor: pointer; transition: color .15s; }}
  table.reels-table thead th[data-sort]:hover {{ color: var(--fg); }}
  table.reels-table thead th.sort-active {{ color: var(--orange); }}
  table.reels-table thead th .arrow {{ display: inline-block; margin-left: 4px; opacity: 0; font-size: 9px; }}
  table.reels-table thead th.sort-active .arrow {{ opacity: 1; }}
  table.reels-table tbody tr {{ border-bottom: 1px solid var(--border); transition: background .12s; cursor: pointer; }}
  table.reels-table tbody tr:hover {{ background: var(--bg-3); }}
  table.reels-table tbody tr:hover .row-expand {{ opacity: 1; }}
  table.reels-table tbody tr:last-child {{ border-bottom: none; }}
  table.reels-table td {{ padding: 8px 14px; vertical-align: middle; height: 36px; line-height: 1.3; }}
  table.reels-table td.num {{ font-variant-numeric: tabular-nums; font-weight: 500; font-feature-settings: "tnum"; text-align: right; white-space: nowrap; }}
  table.reels-table thead th.num {{ text-align: right; }}
  table.reels-table td {{ white-space: nowrap; }}
  table.reels-table td.hook-cell {{ white-space: normal; }}

  td.outlier-cell {{ width: 86px; }}
  .outlier-pill {{ display: inline-flex; align-items: center; justify-content: center; min-width: 54px; padding: 3px 9px; border-radius: 999px; font-size: 11px; font-weight: 700; color: #0a0a0c; font-variant-numeric: tabular-nums; }}
  .outlier-pill.normal {{ background: rgba(255,255,255,.10); color: var(--fg-dim); }}

  td.creator-col {{ width: 140px; }}
  .handle {{ font-size: 12px; font-weight: 500; color: var(--fg-dim); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 130px; display: inline-block; }}
  tr:hover .handle {{ color: var(--fg); }}

  td.hook-cell {{ max-width: 460px; min-width: 320px; }}
  .row-hook {{ font-size: 13px; color: var(--fg); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; display: block; }}
  td.audio-cell {{ font-size: 11px; color: var(--fg-dim); max-width: 140px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
  .row-expand {{ color: var(--orange); font-size: 11px; opacity: 0; transition: opacity .12s; user-select: none; }}

  /* Compact density toggle */
  body[data-density="compact"] table.reels-table td {{ padding: 5px 14px; height: 28px; font-size: 12px; }}
  body[data-density="compact"] table.reels-table td.hook-cell .row-hook {{ font-size: 12px; }}

  /* Per-row checkbox / delete */
  td.action-cell {{ width: 80px; white-space: nowrap; }}
  .row-check {{ width: 18px; height: 18px; border-radius: 5px; border: 1.5px solid var(--border-strong); display: inline-flex; align-items: center; justify-content: center; cursor: pointer; transition: all .12s; background: transparent; vertical-align: middle; }}
  .row-check:hover {{ border-color: var(--orange); }}
  .row-check.checked {{ background: #2DD46F; border-color: #2DD46F; color: #0a0a0c; }}
  .row-check.checked::after {{ content: "✓"; font-size: 12px; font-weight: 700; }}
  .row-delete {{ color: var(--fg-faint); font-size: 14px; margin-left: 8px; cursor: pointer; transition: color .12s; vertical-align: middle; }}
  .row-delete:hover {{ color: var(--pink); }}
  tr.completed {{ opacity: .42; }}
  tr.completed .row-hook {{ text-decoration: line-through; }}

  /* Filter bar */
  .filter-bar {{ display: flex; align-items: center; gap: 10px; flex-wrap: wrap; padding: 14px 16px; background: var(--bg-2); border: 1px solid var(--border); border-radius: 12px; margin-bottom: 12px; }}
  .filter-search {{ flex: 1; min-width: 240px; padding: 8px 12px; background: var(--bg-3); border: 1px solid var(--border); border-radius: 8px; color: var(--fg); font-size: 13px; outline: none; transition: border-color .12s; }}
  .filter-search:focus {{ border-color: var(--orange); }}
  .filter-search::placeholder {{ color: var(--fg-faint); }}
  .band-filter {{ display: inline-flex; gap: 4px; background: var(--bg-3); border: 1px solid var(--border); border-radius: 999px; padding: 3px; }}
  .band-filter button {{ padding: 5px 12px; border-radius: 999px; font-size: 11px; font-weight: 600; color: var(--fg-dim); transition: all .12s; display: inline-flex; align-items: center; gap: 5px; }}
  .band-filter button:hover:not(.active) {{ color: var(--fg); }}
  .band-filter button.active {{ background: var(--fg); color: var(--bg); }}
  .band-filter button .swatch {{ width: 8px; height: 8px; border-radius: 50%; display: inline-block; }}
  .toggle-pill {{ display: inline-flex; align-items: center; gap: 6px; padding: 6px 12px; background: var(--bg-3); border: 1px solid var(--border); border-radius: 999px; font-size: 12px; color: var(--fg-dim); cursor: pointer; transition: all .12s; }}
  .toggle-pill:hover {{ color: var(--fg); }}
  .toggle-pill.on {{ background: rgba(45,212,111,.15); border-color: rgba(45,212,111,.4); color: #2DD46F; }}
  .toggle-pill.on::before {{ content: "✓ "; }}
  .filter-reset {{ font-size: 11px; color: var(--fg-faint); cursor: pointer; padding: 6px 10px; border-radius: 8px; transition: color .12s; }}
  .filter-reset:hover {{ color: var(--pink); }}
  .density-toggle {{ display: inline-flex; gap: 4px; background: var(--bg-2); border: 1px solid var(--border); border-radius: 999px; padding: 3px; margin-left: 8px; }}
  .density-toggle button {{ padding: 6px 12px; border-radius: 999px; font-size: 11px; font-weight: 600; color: var(--fg-dim); transition: all .15s; }}
  .density-toggle button.active {{ background: var(--fg); color: var(--bg); }}
  .density-toggle button:not(.active):hover {{ color: var(--fg); }}

  /* Legend below table */
  .legend {{ display: flex; gap: 18px; font-size: 11px; color: var(--fg-dim); margin: 14px 0 0; flex-wrap: wrap; }}
  .legend .dot {{ display: inline-block; width: 9px; height: 9px; border-radius: 50%; margin-right: 6px; vertical-align: middle; }}

  /* ===== Grid view (secondary) ===== */
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 16px; }}
  .card {{ background: var(--bg-2); border: 1px solid var(--border); border-radius: 14px; overflow: hidden; transition: transform .15s ease, border-color .15s ease; display: flex; flex-direction: column; }}
  .card:hover {{ transform: translateY(-2px); border-color: var(--border-strong); }}
  .card.band-breakout {{ border-color: rgba(255,61,110,.4); box-shadow: 0 0 0 1px rgba(255,61,110,.2); }}
  .card.band-strong {{ border-color: rgba(255,138,61,.35); }}
  .card .thumb {{ position: relative; aspect-ratio: 9/12; display: block; background: var(--bg-3); overflow: hidden; width: 100%; }}
  .card .thumb img {{ width: 100%; height: 100%; object-fit: cover; display: block; transition: transform .25s ease; }}
  .card:hover .thumb img {{ transform: scale(1.04); }}
  .play-overlay {{ position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; font-size: 42px; color: rgba(255,255,255,.92); text-shadow: 0 4px 24px rgba(0,0,0,.6); opacity: 0; transition: opacity .15s ease; pointer-events: none; }}
  .card:hover .play-overlay {{ opacity: 1; }}
  .play-badge {{ position: absolute; bottom: 8px; left: 8px; padding: 3px 8px; background: rgba(0,0,0,.7); border-radius: 999px; font-size: 11px; font-weight: 600; backdrop-filter: blur(4px); }}
  .play-badge::before {{ content: "▶ "; }}
  .band-badge {{ position: absolute; top: 8px; right: 8px; padding: 3px 9px; border-radius: 999px; font-size: 10px; font-weight: 700; color: #0a0a0c; letter-spacing: .02em; }}
  .meta {{ padding: 12px 14px 14px; display: flex; flex-direction: column; gap: 8px; flex: 1; }}
  .creator-row {{ display: flex; align-items: center; gap: 6px; font-size: 11px; color: var(--fg-dim); }}
  .creator-avatar-sm {{ width: 20px; height: 20px; border-radius: 50%; object-fit: cover; }}
  .hook {{ font-size: 13px; line-height: 1.35; font-weight: 500; color: var(--fg); }}
  .stats {{ display: flex; gap: 10px; font-size: 11px; color: var(--fg-dim); border-top: 1px solid var(--border); padding-top: 8px; margin-top: auto; flex-wrap: wrap; }}
  .stats b {{ color: var(--fg); font-weight: 600; }}

  /* ===== Accountability + footer ===== */
  .accountability {{ margin-top: 40px; padding: 20px 24px; background: linear-gradient(135deg, rgba(255,61,110,.08), rgba(255,138,61,.04)); border: 1px solid rgba(255,61,110,.2); border-radius: 14px; }}
  .accountability h3 {{ margin: 0 0 6px; font-size: 16px; font-weight: 600; }}
  .accountability p {{ margin: 0; color: var(--fg-dim); font-size: 13px; }}
  .accountability .ask {{ color: var(--pink); font-weight: 600; }}
  footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid var(--border); display: flex; justify-content: space-between; font-size: 11px; color: var(--fg-faint); }}

  /* ===== MODAL ===== */
  .modal {{ position: fixed; inset: 0; z-index: 1000; display: none; }}
  .modal.open {{ display: block; }}
  .modal-backdrop {{ position: absolute; inset: 0; background: rgba(0,0,0,.78); backdrop-filter: blur(10px); animation: fadeIn .15s ease; }}
  .modal-content {{ position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); width: min(1100px, 95vw); max-height: 92vh; background: var(--bg-2); border: 1px solid var(--border-strong); border-radius: 20px; overflow: hidden; animation: popIn .2s ease; }}
  .modal-close {{ position: absolute; top: 14px; right: 14px; z-index: 2; width: 36px; height: 36px; border-radius: 50%; background: rgba(0,0,0,.6); color: #fff; font-size: 20px; line-height: 1; display: flex; align-items: center; justify-content: center; backdrop-filter: blur(4px); transition: background .15s; }}
  .modal-close:hover {{ background: var(--pink); }}
  .modal-grid {{ display: grid; grid-template-columns: 460px 1fr; gap: 0; width: 100%; max-height: 92vh; }}
  .modal-video {{ background: #000; display: flex; align-items: stretch; justify-content: center; min-height: 600px; position: relative; }}
  .modal-video iframe {{ width: 100%; height: 100%; border: 0; background: #000; }}
  .modal-video video {{ width: 100%; height: 100%; object-fit: cover; background: #000; }}
  .modal-source-toggle {{ position: absolute; bottom: 14px; left: 14px; padding: 8px 14px; border-radius: 999px; background: rgba(0,0,0,.72); color: #fff; font-size: 11px; font-weight: 600; letter-spacing: .04em; text-transform: uppercase; backdrop-filter: blur(6px); border: 1px solid rgba(255,255,255,.15); transition: all .12s; cursor: pointer; }}
  .modal-source-toggle:hover {{ background: var(--orange); color: #0a0a0c; }}
  .hook-clip-badge {{ position: absolute; top: 14px; left: 14px; padding: 4px 10px; border-radius: 999px; background: rgba(255,138,61,.92); color: #0a0a0c; font-size: 10px; font-weight: 700; letter-spacing: .12em; text-transform: uppercase; pointer-events: none; }}
  .modal-info {{ padding: 28px 30px 24px; overflow-y: auto; display: flex; flex-direction: column; gap: 16px; }}
  .modal-info .modal-badge {{ align-self: flex-start; padding: 6px 14px; border-radius: 999px; font-size: 12px; font-weight: 700; color: #0a0a0c; letter-spacing: .02em; }}
  .modal-info h2 {{ font-size: 20px; line-height: 1.3; margin: 0; font-weight: 600; letter-spacing: -.01em; }}
  .modal-creator {{ display: flex; align-items: center; gap: 8px; font-size: 12px; color: var(--fg-dim); }}
  .modal-creator img {{ width: 24px; height: 24px; border-radius: 50%; }}
  .modal-stats {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; padding: 12px 0; border-top: 1px solid var(--border); border-bottom: 1px solid var(--border); }}
  .modal-stat .lab {{ font-size: 10px; letter-spacing: .14em; text-transform: uppercase; color: var(--fg-faint); margin-bottom: 4px; }}
  .modal-stat .val {{ font-size: 18px; font-weight: 600; }}
  .modal-meta {{ font-size: 12px; color: var(--fg-dim); display: flex; gap: 16px; flex-wrap: wrap; }}
  .modal-caption {{ font-size: 13px; line-height: 1.5; color: var(--fg-dim); white-space: pre-wrap; max-height: 180px; overflow-y: auto; padding: 12px; background: var(--bg); border-radius: 10px; border: 1px solid var(--border); }}
  .modal-field-label {{ font-size: 10px; letter-spacing: .14em; text-transform: uppercase; color: var(--fg-faint); margin-top: 4px; font-weight: 600; }}
  .modal-link {{ display: inline-flex; align-items: center; gap: 6px; padding: 9px 16px; background: var(--orange); color: #0a0a0c; border-radius: 10px; font-size: 13px; font-weight: 600; transition: background .15s; align-self: flex-start; }}
  .modal-link:hover {{ background: var(--pink); color: #fff; }}
  @keyframes fadeIn {{ from {{ opacity: 0 }} to {{ opacity: 1 }} }}
  @keyframes popIn {{ from {{ opacity: 0; transform: translate(-50%, -48%) scale(.97) }} to {{ opacity: 1; transform: translate(-50%, -50%) scale(1) }} }}
  @media (max-width: 900px) {{
    .modal-grid {{ grid-template-columns: 1fr; max-height: 92vh; overflow-y: auto; }}
    .modal-video {{ min-height: 480px; }}
  }}
</style>
</head>
<body data-view="table">
<div class="wrap">

  <header class="hero">
    <div>
      <div class="eyebrow">Outlier Lab</div>
      <h1>What's <span class="accent">going viral</span> in your niche today.</h1>
      <p class="sub">Rolling 28-day competitive intel. Outlier ratio = each reel's plays ÷ that account's own median.</p>
    </div>
    <div class="header-meta">
      <div class="date">{today}</div>
      <div>{len(creators)} creator{'' if len(creators)==1 else 's'} · {len(all_rows)} reels tracked</div>
      <div>Next refresh: <b>tomorrow 07:00</b></div>
    </div>
  </header>

  <h3 class="section-title">Creators tracked</h3>
  <div class="creators-row">
    <button class="creator-chip all active" data-creator="__all__" type="button">
      <div class="avatar-fallback" style="display:flex;align-items:center;justify-content:center;font-size:18px">⊕</div>
      <div class="chip-info">
        <div class="chip-name">All creators</div>
        <div class="chip-stats">{len(all_rows)} reels · {len(outliers)} outliers</div>
      </div>
    </button>
    {creator_chips}
  </div>

  <div class="kpis">
    <div class="kpi"><div class="lab">Median plays</div><div class="val">{fmt_num(median_overall)}</div><div class="delta">Across all tracked</div></div>
    <div class="kpi"><div class="lab">Top reel</div><div class="val accent">{fmt_num(max(r['plays'] for r in all_rows))}</div><div class="delta">{all_rows[0]['band_label']} · {all_rows[0]['ratio']:.1f}× median</div></div>
    <div class="kpi"><div class="lab">Total plays · 30d</div><div class="val">{fmt_num(total_plays)}</div><div class="delta">All reels combined</div></div>
    <div class="kpi"><div class="lab">Engagements · 30d</div><div class="val">{fmt_num(total_engagements)}</div><div class="delta">Likes + comments</div></div>
    <div class="kpi"><div class="lab">Outliers (≥2×)</div><div class="val">{len(outliers)}</div><div class="delta">{round(100*len(outliers)/len(all_rows)) if all_rows else 0}% of feed</div></div>
  </div>

  <div class="view-bar">
    <div class="left">
      <h2>Reels</h2>
      <span class="count" id="row-count">{len(all_rows)} of {len(all_rows)}</span>
      <span class="filter-status" id="filter-status"></span>
    </div>
    <div style="display:flex;align-items:center;gap:8px">
      <div class="density-toggle" role="tablist">
        <button data-density="comfy" class="active">Comfy</button>
        <button data-density="compact">Compact</button>
      </div>
      <div class="view-toggle" role="tablist">
        <button data-view="table" class="active">☰ Table</button>
        <button data-view="grid">▦ Grid</button>
      </div>
    </div>
  </div>

  <div class="table-view">
    <div class="filter-bar">
      <input type="text" class="filter-search" id="search-input" placeholder="🔎 Search hooks, captions, transcripts…">
      <div class="band-filter" id="band-filter">
        <button data-band="all" class="active">All</button>
        <button data-band="breakout"><span class="swatch" style="background:#FF3D6E"></span>Breakout</button>
        <button data-band="strong"><span class="swatch" style="background:#FF8A3D"></span>Replicable</button>
        <button data-band="good"><span class="swatch" style="background:#FFD43D"></span>Working</button>
        <button data-band="normal"><span class="swatch" style="background:rgba(255,255,255,.4)"></span>Normal</button>
      </div>
      <button class="toggle-pill" id="toggle-completed" type="button">Hide completed</button>
      <button class="toggle-pill" id="toggle-deleted" type="button">Show deleted</button>
      <span class="filter-reset" id="filter-reset">Reset filters</span>
    </div>
    <div class="table-wrap">
      <table class="reels-table">
        <thead>
          <tr>
            <th></th>
            <th data-sort="ratio">Outlier<span class="arrow">▼</span></th>
            <th data-sort="creator_username" class="creator-col">Creator<span class="arrow">▼</span></th>
            <th>Hook (spoken)</th>
            <th data-sort="plays" class="num">Plays<span class="arrow">▼</span></th>
            <th data-sort="likes" class="num">Likes<span class="arrow">▼</span></th>
            <th data-sort="comments" class="num">Comments<span class="arrow">▼</span></th>
            <th data-sort="engagements" class="num">Engagements<span class="arrow">▼</span></th>
            <th data-sort="duration" class="num">Length<span class="arrow">▼</span></th>
            <th data-sort="posted_ts" class="sort-active sort-desc">Posted<span class="arrow">▼</span></th>
            <th></th>
          </tr>
        </thead>
        <tbody id="reels-tbody"></tbody>
      </table>
    </div>
    <div class="legend">
      <span><span class="dot" style="background:#FF3D6E"></span>Breakout (≥15×) — usually unrepeatable</span>
      <span><span class="dot" style="background:#FF8A3D"></span>Replicable (5–15×) — the sweet spot</span>
      <span><span class="dot" style="background:#FFD43D"></span>Working (2–5×) — note the pattern</span>
      <span><span class="dot" style="background:rgba(255,255,255,.4)"></span>Normal (&lt;2×)</span>
    </div>
  </div>

  <div class="grid-view">
    <div class="grid">{cards}</div>
  </div>

  <div class="accountability">
    <h3>🔥 The only metric that compounds: reps shipped.</h3>
    <p><span class="ask">Have you posted a reel today?</span> Watching what others posted is not posting. Pick one pattern. Close this tab. Film.</p>
  </div>

  <footer>
    <div>Outlier Lab · v1.2 · {len(creators)} creator{'' if len(creators)==1 else 's'} tracked — multi-account list comes next</div>
    <div>Data: Apify · Built {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
  </footer>

</div>

<div class="modal" id="modal" aria-hidden="true">
  <div class="modal-backdrop" data-close></div>
  <div class="modal-content">
    <button class="modal-close" data-close aria-label="Close">×</button>
    <div class="modal-grid">
      <div class="modal-video">
        <video id="modal-video" autoplay muted loop playsinline preload="metadata" hidden></video>
        <iframe id="modal-iframe" src="" frameborder="0" scrolling="no" allowtransparency="true" allow="autoplay; encrypted-media" hidden></iframe>
        <span class="hook-clip-badge" id="modal-clip-badge" hidden>● Hook · first 3s · muted</span>
        <button class="modal-source-toggle" id="modal-source-toggle" type="button" hidden>Show full reel ↗</button>
      </div>
      <div class="modal-info">
        <div id="modal-badge" class="modal-badge">—</div>
        <div id="modal-creator" class="modal-creator"></div>
        <h2 id="modal-hook">—</h2>
        <div class="modal-stats" id="modal-stats"></div>
        <div class="modal-meta" id="modal-meta"></div>
        <div class="modal-field-label">Transcript</div>
        <div class="modal-caption" id="modal-transcript">—</div>
        <div class="modal-field-label">Description (caption)</div>
        <div class="modal-caption" id="modal-caption">—</div>
        <a id="modal-link" class="modal-link" href="#" target="_blank" rel="noopener">Open on Instagram ↗</a>
      </div>
    </div>
  </div>
</div>

<script>
const REELS = {reels_payload};
const CREATORS = {creators_payload};

const fmtNum = (n) => {{
  if (n === null || n === undefined) return "—";
  n = Number(n);
  if (n >= 1e6) return (n/1e6).toFixed(1) + "M";
  if (n >= 1e4) return Math.round(n/1e3) + "K";
  if (n >= 1e3) return (n/1e3).toFixed(1) + "K";
  return String(Math.round(n));
}};
const fmtDur = (s) => {{
  if (!s) return "—";
  s = Math.round(s);
  const m = Math.floor(s/60);
  const sec = s % 60;
  return m ? `${{m}}:${{sec.toString().padStart(2,"0")}}` : `${{s}}s`;
}};
function escapeHtml(s) {{
  if (!s) return "";
  return String(s).replace(/[&<>"']/g, c => ({{"&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;","'":"&#39;"}})[c]);
}}

// ---- State ----
const VIEW_KEY = "ig-dashboard-view";
const FILTER_KEY = "ig-dashboard-filter";
const COMPLETED_KEY = "ig-dashboard-completed";
const DELETED_KEY = "ig-dashboard-deleted";
const SEARCH_KEY = "ig-dashboard-search";
const BAND_KEY = "ig-dashboard-band";
const HIDE_COMPLETED_KEY = "ig-dashboard-hide-completed";
const SHOW_DELETED_KEY = "ig-dashboard-show-deleted";

let activeFilter = localStorage.getItem(FILTER_KEY) || "__all__";
let completed = new Set(JSON.parse(localStorage.getItem(COMPLETED_KEY) || "[]"));
let deleted = new Set(JSON.parse(localStorage.getItem(DELETED_KEY) || "[]"));
let searchText = localStorage.getItem(SEARCH_KEY) || "";
let bandFilter = localStorage.getItem(BAND_KEY) || "all";
let hideCompleted = localStorage.getItem(HIDE_COMPLETED_KEY) === "1";
let showDeleted = localStorage.getItem(SHOW_DELETED_KEY) === "1";
let sortKey = "posted_ts";
let sortDir = "desc";

function saveState() {{
  localStorage.setItem(COMPLETED_KEY, JSON.stringify([...completed]));
  localStorage.setItem(DELETED_KEY, JSON.stringify([...deleted]));
  localStorage.setItem(SEARCH_KEY, searchText);
  localStorage.setItem(BAND_KEY, bandFilter);
  localStorage.setItem(HIDE_COMPLETED_KEY, hideCompleted ? "1" : "0");
  localStorage.setItem(SHOW_DELETED_KEY, showDeleted ? "1" : "0");
}}

function getFiltered() {{
  let rows = REELS;
  if (activeFilter !== "__all__") rows = rows.filter(r => r.creator_handle === activeFilter);
  if (bandFilter !== "all") rows = rows.filter(r => r.band_class === bandFilter);
  if (searchText.trim()) {{
    const q = searchText.trim().toLowerCase();
    rows = rows.filter(r =>
      (r.hook || "").toLowerCase().includes(q) ||
      (r.caption || "").toLowerCase().includes(q) ||
      (r.transcript || "").toLowerCase().includes(q) ||
      (r.creator_username || "").toLowerCase().includes(q)
    );
  }}
  if (!showDeleted) rows = rows.filter(r => !deleted.has(r.shortCode));
  if (hideCompleted) rows = rows.filter(r => !completed.has(r.shortCode));
  return rows;
}}

// ---- Filter (creator chips) ----
function applyFilter(handle) {{
  activeFilter = handle;
  localStorage.setItem(FILTER_KEY, handle);
  document.querySelectorAll(".creator-chip").forEach(c =>
    c.classList.toggle("active", c.dataset.creator === handle));
  const filtered = getFiltered();
  document.getElementById("row-count").textContent = `${{filtered.length}} of ${{REELS.length}}`;
  const status = document.getElementById("filter-status");
  if (handle === "__all__") {{
    status.innerHTML = "";
  }} else {{
    const c = CREATORS.find(c => c.handle === handle);
    status.innerHTML = `<span class="pill">filtered: @${{escapeHtml(c.username)}} <button data-clear>×</button></span>`;
    status.querySelector("[data-clear]").addEventListener("click", () => applyFilter("__all__"));
  }}
  renderTable();
  renderGrid();
}}

document.querySelectorAll(".creator-chip").forEach(c => {{
  c.addEventListener("click", () => applyFilter(c.dataset.creator));
}});

// ---- View toggle ----
function setView(v) {{
  document.body.dataset.view = v;
  localStorage.setItem(VIEW_KEY, v);
  document.querySelectorAll(".view-toggle button").forEach(b =>
    b.classList.toggle("active", b.dataset.view === v));
}}
document.querySelectorAll(".view-toggle button").forEach(b => {{
  b.addEventListener("click", () => setView(b.dataset.view));
}});
setView(localStorage.getItem(VIEW_KEY) || "table");

// ---- Density toggle ----
const DENSITY_KEY = "ig-dashboard-density";
function setDensity(d) {{
  document.body.dataset.density = d;
  localStorage.setItem(DENSITY_KEY, d);
  document.querySelectorAll(".density-toggle button").forEach(b =>
    b.classList.toggle("active", b.dataset.density === d));
}}
document.querySelectorAll(".density-toggle button").forEach(b => {{
  b.addEventListener("click", () => setDensity(b.dataset.density));
}});
setDensity(localStorage.getItem(DENSITY_KEY) || "comfy");

// ---- Table render + sort ----
function renderTable() {{
  const tbody = document.getElementById("reels-tbody");
  const rows = [...getFiltered()].sort((a, b) => {{
    const va = a[sortKey], vb = b[sortKey];
    const na = typeof va === "number" ? va : (va || "");
    const nb = typeof vb === "number" ? vb : (vb || "");
    if (typeof na === "string" || typeof nb === "string") {{
      return sortDir === "desc" ? String(nb).localeCompare(String(na)) : String(na).localeCompare(String(nb));
    }}
    return sortDir === "desc" ? nb - na : na - nb;
  }});
  tbody.innerHTML = rows.map(r => {{
    const ratioStr = r.ratio ? r.ratio.toFixed(1) + "×" : "—";
    const pillClass = r.band_class === "normal" ? "outlier-pill normal" : "outlier-pill";
    const pillStyle = r.band_class === "normal" ? "" : `style="background:${{r.band_color}}"`;
    const isDone = completed.has(r.shortCode);
    const isDel = deleted.has(r.shortCode);
    return `
      <tr data-shortcode="${{r.shortCode}}" class="${{isDone ? 'completed' : ''}} ${{isDel ? 'deleted' : ''}}">
        <td class="action-cell" onclick="event.stopPropagation()">
          <button class="row-check ${{isDone ? 'checked' : ''}}" data-action="toggle-done" aria-label="Mark complete"></button>
          <span class="row-delete" data-action="${{isDel ? 'restore' : 'delete'}}" title="${{isDel ? 'Restore' : 'Remove from view'}}">${{isDel ? '↺' : '×'}}</span>
        </td>
        <td class="outlier-cell">
          <span class="${{pillClass}}" ${{pillStyle}}>${{ratioStr}}</span>
        </td>
        <td class="creator-col">
          <span class="handle">@${{escapeHtml(r.creator_username)}}</span>
        </td>
        <td class="hook-cell">
          <span class="row-hook" title="${{escapeHtml(r.hook || '')}}">${{r.hook ? escapeHtml(r.hook) : "<em>no hook</em>"}}</span>
        </td>
        <td class="num">${{fmtNum(r.plays)}}</td>
        <td class="num">${{fmtNum(r.likes)}}</td>
        <td class="num">${{fmtNum(r.comments)}}</td>
        <td class="num">${{fmtNum(r.engagements)}}</td>
        <td class="num">${{fmtDur(r.duration)}}</td>
        <td>${{escapeHtml(r.posted_human)}}</td>
        <td><span class="row-expand">expand ↗</span></td>
      </tr>
    `;
  }}).join("");
}}

function renderGrid() {{
  document.querySelectorAll(".grid-view .card").forEach(card => {{
    const show = activeFilter === "__all__" || card.dataset.creator === activeFilter;
    card.style.display = show ? "" : "none";
  }});
}}

document.querySelectorAll("th[data-sort]").forEach(th => {{
  th.addEventListener("click", () => {{
    const key = th.dataset.sort;
    if (key === sortKey) {{
      sortDir = sortDir === "desc" ? "asc" : "desc";
    }} else {{
      sortKey = key;
      sortDir = "desc";
    }}
    document.querySelectorAll("th[data-sort]").forEach(t => {{
      t.classList.remove("sort-active","sort-desc","sort-asc");
      t.querySelector(".arrow").textContent = "▼";
    }});
    th.classList.add("sort-active", `sort-${{sortDir}}`);
    th.querySelector(".arrow").textContent = sortDir === "desc" ? "▼" : "▲";
    renderTable();
  }});
}});

// Init
applyFilter(activeFilter);

// ---- Modal ----
const modal = document.getElementById("modal");
const modalIframe = document.getElementById("modal-iframe");
const modalVideo = document.getElementById("modal-video");
const modalBadge = document.getElementById("modal-clip-badge");
const modalSourceToggle = document.getElementById("modal-source-toggle");

let modalCurrentShortCode = null;
let modalShowingClip = true;

function showClipMode(shortCode) {{
  modalShowingClip = true;
  modalVideo.src = `clips/${{shortCode}}.mp4`;
  modalVideo.hidden = false;
  modalVideo.play().catch(()=>{{}});
  modalIframe.src = "";
  modalIframe.hidden = true;
  modalBadge.hidden = false;
  modalSourceToggle.hidden = false;
  modalSourceToggle.textContent = "Show full reel ↗";
}}

function showIframeMode(shortCode) {{
  modalShowingClip = false;
  modalVideo.pause();
  modalVideo.src = "";
  modalVideo.hidden = true;
  modalIframe.src = `https://www.instagram.com/p/${{shortCode}}/embed/captioned/`;
  modalIframe.hidden = false;
  modalBadge.hidden = true;
  modalSourceToggle.hidden = false;
  modalSourceToggle.textContent = "← Back to hook";
}}

modalSourceToggle.addEventListener("click", () => {{
  if (!modalCurrentShortCode) return;
  if (modalShowingClip) showIframeMode(modalCurrentShortCode);
  else showClipMode(modalCurrentShortCode);
}});

function openModal(shortCode) {{
  const r = REELS.find(x => x.shortCode === shortCode);
  if (!r) return;
  modalCurrentShortCode = shortCode;
  if (r.hasClip) {{
    showClipMode(shortCode);
  }} else {{
    showIframeMode(shortCode);
    modalSourceToggle.hidden = true;  // no clip to toggle back to
  }}
  document.getElementById("modal-hook").textContent = r.hook || "(no hook)";
  const badge = document.getElementById("modal-badge");
  badge.textContent = (r.ratio ? r.ratio.toFixed(1) + "× · " : "") + r.band_label;
  badge.style.background = r.band_color;
  badge.style.color = r.band_class === "normal" ? "rgba(244,244,246,.6)" : "#0a0a0c";
  document.getElementById("modal-creator").innerHTML = r.creator_avatar
    ? `<img src="${{r.creator_avatar}}" alt=""><span>@${{escapeHtml(r.creator_username)}}</span>`
    : `<span>@${{escapeHtml(r.creator_username)}}</span>`;
  document.getElementById("modal-stats").innerHTML = `
    <div class="modal-stat"><div class="lab">Plays</div><div class="val">${{fmtNum(r.plays)}}</div></div>
    <div class="modal-stat"><div class="lab">Engagements</div><div class="val">${{fmtNum(r.engagements)}}</div></div>
    <div class="modal-stat"><div class="lab">Likes</div><div class="val">${{fmtNum(r.likes)}}</div></div>
    <div class="modal-stat"><div class="lab">Comments</div><div class="val">${{fmtNum(r.comments)}}</div></div>
  `;
  document.getElementById("modal-meta").innerHTML = `
    <span>⏱ ${{fmtDur(r.duration)}}</span>
    <span>📅 ${{escapeHtml(r.posted_human)}}</span>
  `;
  document.getElementById("modal-transcript").textContent = r.transcript || "(no transcript)";
  document.getElementById("modal-caption").textContent = r.caption || "(no caption)";
  document.getElementById("modal-link").href = r.url;
  modal.classList.add("open");
  modal.setAttribute("aria-hidden", "false");
  document.body.style.overflow = "hidden";
}}

function closeModal() {{
  modal.classList.remove("open");
  modal.setAttribute("aria-hidden", "true");
  modalIframe.src = "";
  modalVideo.pause();
  modalVideo.src = "";
  modalVideo.hidden = true;
  modalIframe.hidden = true;
  modalBadge.hidden = true;
  modalSourceToggle.hidden = true;
  modalCurrentShortCode = null;
  document.body.style.overflow = "";
}}

modal.addEventListener("click", e => {{
  if (e.target.hasAttribute("data-close")) closeModal();
}});
document.addEventListener("keydown", e => {{
  if (e.key === "Escape" && modal.classList.contains("open")) closeModal();
}});

document.querySelectorAll(".card[data-shortcode] .thumb").forEach(t => {{
  t.addEventListener("click", () => openModal(t.closest(".card").dataset.shortcode));
}});

// Table row clicks: open modal unless clicking checkbox/delete
document.addEventListener("click", e => {{
  // checkbox toggle
  if (e.target.matches(".row-check, .row-check *")) {{
    e.stopPropagation();
    const row = e.target.closest("tr[data-shortcode]");
    const sc = row.dataset.shortcode;
    if (completed.has(sc)) completed.delete(sc); else completed.add(sc);
    saveState();
    renderTable();
    return;
  }}
  // delete / restore
  if (e.target.matches(".row-delete")) {{
    e.stopPropagation();
    const row = e.target.closest("tr[data-shortcode]");
    const sc = row.dataset.shortcode;
    const action = e.target.dataset.action;
    if (action === "delete") {{
      deleted.add(sc);
    }} else {{
      deleted.delete(sc);
    }}
    saveState();
    renderTable();
    updateRowCount();
    return;
  }}
  // expand row -> modal
  const row = e.target.closest("tr[data-shortcode]");
  if (row && !e.target.closest(".action-cell")) {{
    openModal(row.dataset.shortcode);
  }}
}});

// Filter bar
const searchInput = document.getElementById("search-input");
searchInput.value = searchText;
searchInput.addEventListener("input", () => {{
  searchText = searchInput.value;
  saveState();
  renderTable();
  updateRowCount();
}});

document.querySelectorAll("#band-filter button").forEach(b => {{
  if (b.dataset.band === bandFilter) {{
    document.querySelectorAll("#band-filter button").forEach(x => x.classList.remove("active"));
    b.classList.add("active");
  }}
  b.addEventListener("click", () => {{
    bandFilter = b.dataset.band;
    document.querySelectorAll("#band-filter button").forEach(x => x.classList.remove("active"));
    b.classList.add("active");
    saveState();
    renderTable();
    updateRowCount();
  }});
}});

const tCompleted = document.getElementById("toggle-completed");
const tDeleted = document.getElementById("toggle-deleted");
function syncToggles() {{
  tCompleted.classList.toggle("on", hideCompleted);
  tCompleted.textContent = hideCompleted ? "Hiding completed" : "Hide completed";
  tDeleted.classList.toggle("on", showDeleted);
  tDeleted.textContent = showDeleted ? "Showing deleted" : "Show deleted";
}}
tCompleted.addEventListener("click", () => {{
  hideCompleted = !hideCompleted;
  syncToggles();
  saveState();
  renderTable();
  updateRowCount();
}});
tDeleted.addEventListener("click", () => {{
  showDeleted = !showDeleted;
  syncToggles();
  saveState();
  renderTable();
  updateRowCount();
}});
syncToggles();

document.getElementById("filter-reset").addEventListener("click", () => {{
  searchText = "";
  bandFilter = "all";
  hideCompleted = false;
  showDeleted = false;
  searchInput.value = "";
  document.querySelectorAll("#band-filter button").forEach(x => x.classList.remove("active"));
  document.querySelector('#band-filter button[data-band="all"]').classList.add("active");
  syncToggles();
  saveState();
  renderTable();
  updateRowCount();
}});

function updateRowCount() {{
  document.getElementById("row-count").textContent = `${{getFiltered().length}} of ${{REELS.length}}`;
}}
</script>
</body>
</html>
"""

    OUT.write_text(html)
    print(f"\n✓ Wrote {OUT}")
    print(f"  {len(creators)} creator(s) · {len(all_rows)} reels · {len(outliers)} outliers (≥2×)")
    if all_rows:
        print(f"  Top reel: {fmt_num(all_rows[0]['plays'])} plays, {all_rows[0]['ratio']:.1f}× median by @{all_rows[0]['creator_username']}")


if __name__ == "__main__":
    main()
